// Central lookup from a DB-stored icon name (string) to its lucide-react
// component. Keeping this in one place lets admin-managed content
// (services, features, page items) reference icons by name while the
// actual component set stays a fixed, safe allow-list.
import {
  Smartphone,
  Laptop,
  GraduationCap,
  Wrench,
  Headphones,
  FileCode2,
  Cpu,
  ShieldCheck,
  Award,
  Truck,
  Zap,
  MapPin,
  Phone,
  Clock,
  Navigation,
  Sparkles,
  ArrowRight,
  Play,
  CheckCircle2,
  Send,
  ArrowUp,
  Menu,
  X,
  User,
  ExternalLink,
  ScanSearch,
  FileSearch,
  Microscope,
  Star,
  Mail,
  Download,
  Package,
  Settings,
  BookOpen,
  Monitor,
  Battery,
  HardDrive,
} from "lucide-react";

export const ICON_MAP = {
  Smartphone,
  Laptop,
  GraduationCap,
  Wrench,
  Headphones,
  FileCode2,
  Cpu,
  ShieldCheck,
  Award,
  Truck,
  Zap,
  MapPin,
  Phone,
  Clock,
  Navigation,
  Sparkles,
  ArrowRight,
  Play,
  CheckCircle2,
  Send,
  ArrowUp,
  Menu,
  X,
  User,
  ExternalLink,
  ScanSearch,
  FileSearch,
  Microscope,
  Star,
  Mail,
  Download,
  Package,
  Settings,
  BookOpen,
  Monitor,
  Battery,
  HardDrive,
};

export const ICON_NAMES = Object.keys(ICON_MAP);

/** Resolve an icon name to its component, falling back to Star. */
export function getIcon(name) {
  return ICON_MAP[name] || Star;
}
